# Generated by Django 3.1.7 on 2021-03-29 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0004_comments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
    ]
