# Generated by Django 3.1.7 on 2021-03-30 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0006_comment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='status',
        ),
    ]
